[project]
name = "mpipi_lammps_gen"
version = "0.1.0"

dependencies = ["numpy"]

requires-python = ">= 3.10"
authors = [
    { name = "Moritz Sallermann", email = "mos19@hi.is" },
    { name = "Amrita Goswami", email = "amrita@hi.is" },
]

license-files = ["LICEN[CS]E*"]
